server:
  port: 9762

spring:
  application:
    name: service-hi

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: service-hi
    prefer-ip-address: true
