server:
  port: 9861

spring:
  application:
    name: service-ribbon
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

endpoints:
  actuator:
    enabled: true
    sensitive: false
  enabled: true
  health:
    enabled: true
    sensitive: false
management:
  security:
    enabled: false
